In [6]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np
np.__version__

'2.1.0'

action:
|-----|
|0|1|2|
|3|4|5|
|6|7|8|
|-----|



In [8]:
class TicTacToe:
    def __init__(self):
        self.row_count: int = 3
        self.column_count: int = 3
        self.action_size: int = self.row_count * self.column_count
        
    def get_initial_state(self) -> np.ndarray:
        return np.zeros((self.row_count, self.column_count))
    
    def get_row_column(self, action: int) -> tuple[int, int]:
        row = action // self.column_count
        column = action % self.column_count
        return row, column
    
    def get_next_state(self, state: np.ndarray, action: int, player: int) -> np.ndarray:
        row, column = self.get_row_column(action)
        state[row, column] = player
        return state
    
    def get_valid_moves(self, state: np.ndarray) -> (np.uint8):
        # state as 1 dimension vector, then convert boolean to 0(false) or 1(true)
        return (state.reshape(-1) == 0).astype(np.uint8)
    
    def check_win(self, state: np.ndarray, action: int):
        row, column = self.get_row_column(action)
        player = state[row, column]
        
        return (
            np.sum(state[row, :]) == player * self.column_count
            or np.sum(state[:, column]) == player * self.row_count
            or np.sum(np.diag(state)) == player * self.row_count
            or np.sum(np.diag(np.flip(state, axis=0))) == player * self.row_count
        )
    
    def get_value_and_terminated(self, state: np.ndarray, action: int) -> tuple[int, bool]:
        # value is 1 if win, 0 otherwise
        if self.check_win(state, action):
            return 1, True
        if np.sum(self.get_valid_moves(state)) == 0:
            return 0, True
        return 0, False
    
    def get_opponent(self, player: int) -> int:
        return -player

In [9]:
tictactoe = TicTacToe()
player = 1

state = tictactoe.get_initial_state()


while True:
    print(state)
    valid_moves = tictactoe.get_valid_moves(state)
    print("valid_moves", [i for i in range(tictactoe.action_size) if valid_moves[i] == 1])
    action = int(input(f"{player}:"))
    
    if valid_moves[action] == 0:
        print("action not valid")
        continue
        
    state = tictactoe.get_next_state(state, action, player)
    
    value, is_terminal = tictactoe.get_value_and_terminated(state, action)
    
    if is_terminal:
        print(state)
        if value == 1:
            print(player, "won")
        else:
            print("draw")
        break
        
    player = tictactoe.get_opponent(player)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
valid_moves [0, 1, 2, 3, 4, 5, 6, 7, 8]
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
valid_moves [0, 2, 3, 4, 5, 6, 7, 8]
[[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  0.]]
valid_moves [0, 2, 4, 5, 6, 7, 8]


ValueError: invalid literal for int() with base 10: ''